#!/usr/bin/env groovy
@Library('olympus@master') _

olympus.tagGeneratorName = "s3cmd"
olympus.namespace = 'data-platform'
olympus.previewBranch = 'develop'
olympus.productionBranch = 'main'



node('docker') {


    stage('Checkout') {
        checkout scm
    }

    stage('Build & Push images') {
        withDockerScopedCredentials([[
            credentialsId:  'quay-robot',
            url: 'quay.dc.xing.com',
        ]]) {
            def customImage = docker.build("data-platform/s3cmd:${env.BUILD_ID}", "./docker")
            customedImage.push('latest')
            customImage.push()
        }
    }

}