#!/usr/bin/env groovy
@Library('olympus@master') _

olympus.tagGeneratorName = "s3cmd"
olympus.namespace = 'data-platform'
olympus.previewBranch = 'develop'
olympus.productionBranch = 'main'



node('docker') {
    stage('Checkout') {
        checkout scm
    }

    stage('Build images') {
        withDockerScopedCredentials([[
            credentialsId:  'quay-robot',
            url: 'quay.dc.xing.com',
        ]]) {
            sh"docker build -t quay.dc.xing.com/data-platform/s3cmd -f docker/Dockerfile docker"
        }
    }

    stage('Push images') {
        withDockerScopedCredentials([[
            credentialsId:  'quay-robot',
            url: 'quay.dc.xing.com',
        ]]) {
            sh"docker push quay.dc.xing.com/data-platform/s3cmd"
        }
    }


}